### ISSUE TITLE
Whitespace / indent issues

### ISSUE THREAD

**Issue by abligh** [disconnect/apache-websocket#11]
According to
 http://httpd.apache.org/dev/styleguide.html

code should be written a form such that
 indent -i4 -npsl -di0 -br -nce -d0 -cli0 -npcs -nfc1 -nut

produces no differences. This is not the case with this project; currently it uses 2 space indents.

**Comment by disconnect** [comment]
There is some flexibility in the guidelines, thus the output need not match exactly.
