### ISSUE TITLE
Only getting 404s on Apache 2.4

### ISSUE THREAD

**Issue by grjones** [disconnect/apache-websocket#12]
Has anyone else tried using Apache 2.4?  Apache Websocket compiles, but I can only ever get a 404 for the echo test.  There is no mention of the websocket module in the Apache log set to debug log level.  The only thing of relevance I see in the log is:

AH00128: File does not exist: /usr/local/apache2/htdocs/echo

**Comment by disconnect** [comment]
No, I haven't tried Apache 2.4 yet. That looks like the module isn't handling the request. I'll give it a try and report back.

**Comment by disconnect** [comment]
Alright, I installed Apache 2.4 and was able to get the module working without a problem. Make sure that you are picking up the correct include files if you also have Apache 2.2 installed. Verify that you are installing the modules in the proper directory. Confirm that the module is being included (i.e., httpd -M | grep websocket). Include the full path to httpd to make sure you are running the proper version.  Try apachectl configtest (again, include the full path to the Apache 2.4 version). There shouldn't be any errors regarding loading the plugin modules.

**Comment by grjones** [comment]
Ok.  I'll try again.  Thank you for checking.  It must be configuration issue, though I can't seem to find it.  I will keep looking.
