### ISSUE TITLE
Creating custom plugin problem

### ISSUE THREAD

**Issue by baberone** [disconnect/apache-websocket#13]
Hi Disconnect,

I'm trying to create a custom plugin but I've some trouble having it working. As a matter of fact, I have now stripped it down to being exactly the same as the echo plugin, but it still doesn't work! I've updated 'sconstruct' and it compiles fine. When restarting apache I don't have any error messages.
The new module is currently called 'mod_websocket_server'. I've also created a separate html file to test it. 

Is it ok to have it loaded next to the 'echo' plugin ? And is there a possibility some debug information (on init, on connect, etc). 

I'm a noob in creating plugins for apache modules, so excuse me if I overlookied the obvious.

Thanks in advance!
Benoit

---
# include "websocket_plugin.h"
# include "apr_memcache.h"

static size_t CALLBACK server_on_message(void *plugin_private, const WebSocketServer *server,
    const int type, unsigned char *buffer, const size_t buffer_size)
{
  return server->send(server, type, buffer, buffer_size);
}

static WebSocketPlugin s_plugin = {
  sizeof(WebSocketPlugin),
  WEBSOCKET_PLUGIN_VERSION_0,
  NULL, /\* destroy _/
  NULL, /_ on_connect _/
  server_on_message,
  NULL /_ on_disconnect */
};

extern EXPORT WebSocketPlugin \* CALLBACK server_init()
{
  return &s_plugin;
}

---

<IfModule mod_websocket.c>
  <Location /echo>
    SetHandler websocket-handler
    WebSocketHandler /usr/lib/apache2/modules/mod_websocket_echo.so echo_init
  </Location>
  <Location /dumb-increment>
    SetHandler websocket-handler
    WebSocketHandler /usr/lib/apache2/modules/mod_websocket_dumb_increment.so dumb_increment_init
  </Location>
  <Location /server>
    SetHandler websocket-handler
    WebSocketHandler /usr/lib/apache2/modules/mod_websocket_server.so server_init
  </Location>
</IfModule>

**Comment by disconnect** [comment]
I'm assuming that you got the echo plugin to work. What did you call your html file and what is the path to your plugin? You showed the handlers for the various plugins, but not the surrounding <Location /path> ... </Location>. You will run into a problem if you use the same full path name for the WebSocket plugin and the html file. If, for instance, you called both of them 'server', it won't work. That is, http://localhost/server.html for the html file and http://localhost/server for the WebSocket location will fail. It should be fine if the paths are slightly different (e.g., http://localhost/ws/server). That is why I called my test file client.html, not echo.html.

**Comment by baberone** [comment]
Yes the echo (and dumb-increment) are working very well! 

I did indeed call the html page "server.html'. I just fixed it! I renamed the html file and it's working ! thanks!

I'll close this issue.
