### ISSUE TITLE
CentOS6 - Could not find initialization function in module - help?

### ISSUE THREAD

**Issue by scoobydooxp** [disconnect/apache-websocket#19]
I tried adding the section below to http.conf on CentOS6 after running:

sudo apxs -i -a -c mod_websocket.c
sudo apxs -i -a -c mod_websocket_draft76.c

sudo apachectl configtest errors with the line with echo_init and the error: Could not find initialization function in module

I trading changing it to all the various options show in the README file without luck. Any suggestions please?

Thank you,
AP

----- http.conf ------

LoadModule websocket_module   modules/mod_websocket.so
LoadModule websocket_draft76_module modules/mod_websocket_draft76.so

<IfModule mod_websocket.c>
  <Location /echo>
    SetHandler websocket-handler
    WebSocketHandler modules/mod_websocket.so echo_init
  </Location>
</IfModule>

<IfModule mod_websocket_draft76.c>
  <Location /echo>
    SetHandler websocket-handler
    WebSocketHandler modules/mod_websocket_draft76.so echo_init
    SupportDraft75 On
  </Location>
</IfModule>

----- http.conf ------

**Comment by scoobydooxp** [comment]
That did not work well. Please see http://pastebin.com/qjbSDudf for the httpd.conf changes I made.

**Comment by disconnect** [comment]
You need to build the echo example plugin library and load the echo_init function from <em>that</em> (mod_websocket_echo.so) library:

```
WebSocketHandler modules/mod_websocket_echo.so echo_init
```

You are incorrectly trying to load from the mod_websocket.so controller module.
